services:
  app:
    build: .
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_app
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

